config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

#利用者
  
  namespace :users do
    get 'users/unsubscribe'
    patch 'users/withdraw'
    resources :users, only: [:show, :edit, :update]
    resources :subscriptions, only: [:index, :show]
    resources :join_carts, only: [:index, :create, :destroy]
    get "joins/confirm" => "joins#confirm"
    post "joins/confirm" => "joins#confirm"
    get "joins/complete" => "joins#complete"
    resources :books, only: [:index, :show] do
     resource :book_comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
    end
    resources :book_carts, only: [:create, :destroy]
    resources :contacts, only: [:new, :create, :destroy, :index]
    resources :genres, only: [:show]
  end
  
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  registrations: 'users/registrations'
}

#管理者
  
  namespace :admins do
    #resources :subscriptions, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :books, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :edit, :create, :destroy, :update]
    resources :contacts, only: [:index]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  attachment :image
  has_many :book_carts, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true
  validates :image, presence: true 
  validates :descript, presence: true
  validates :author, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def comment_count(book)
    book_comments.count
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :join_carts, dependent: :destroy
  has_many :book_carts, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :contacts, dependent: :destroy
  
  def same?(current_)
    self == current_user
  end
  
  def create_book_comment(book_comment_params,book)
    comment = book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
  end
end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @book = Book.new
    @genres = Genre.all
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to admins_books_path
    else
      render :new
    end
  end

  def index
    @books = Book.all
    @genres = Genre.all
  end

  def edit
    @book = Book.find(params[:id])
    @genres = Genre.all
  end
  
  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @genres = Genre.all
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to admins_books_path #一覧画面へ
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to admins_books_path  #一覧画面へ
  end
  
  private
    
  def book_params
    params.require(:book).permit(:name, :image, :author, :descript, :genre_id, :is_active)
  end
  
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
  @users = User.all
  end

  def show
  @user = User.find(params[:id])
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
  @user.update(user_paramas)
  redirect_to admins_users_path(@user.id)
  end

  private
  def user_paramas
    params.require(:user).permit(:name,:postal_code,:phone_number,:email,:address,:is_deleted)
  end
end

app/controllers/users/book_carts_controller.rb
class Users::BookCartsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book_cart = current_user.book_carts.new(book_cart_params)
    @book_cart.save
    redirect_to users_user_path(current_user.id)
  end
  
  def destroy
    book_cart = BookCart.find(params[:id])
    book_cart.destroy
    redirect_to users_user_path(current_user.id)
  end
  
  private
  def book_cart_params
    params.require(:book_cart).permit(:book_id, :user_id)
  end
end

app/controllers/users/book_comments_controller.rb
class Users::BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    current_user.create_book_comment(book_comment_params,book)
    redirect_to users_book_path(book)
  end

  def destroy
    BookComment.find_by(params[:book_id]).destroy
    redirect_to users_book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/users/books_controller.rb
class Users::BooksController < ApplicationController
  before_action :authenticate_user!
  
  helper_method :sort_column, :sort_direction
  
  def index
    @books = Book.order("#{sort_column} #{sort_direction}") 
    @genres = Genre.all
  end

  def show
    @book = Book.find(params[:id])
    @book_cart = BookCart.new
    @book_comment = BookComment.new
    @genres = Genre.all
  end
  
private

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
    
    def sort_column
      Book.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @contact = current_user.contacts.new(contact_params)
    if @contact.save
     redirect_to users_contacts_path
    else
     render new_users_contact_path
    end
  end

  def index
    @user = current_user
    @contacts = current_user.contacts.all
    @genres = Genre.all
  end
  
  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy
    redirect_to users_contacts_path
  end
  
  private
  def contact_params
    params.permit(:title, :massage)
  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    #非同期のためredirect消す
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    #非同期のためredirect消す
  end
  
end

app/controllers/users/inquiries_controller.rb
class Users::InquiriesController < ApplicationController

end

app/controllers/users/join_carts_controller.rb
class Users::JoinCartsController < ApplicationController
  def index
    @join_carts = JoinCart.all
  end
  
  def create
    @join_cart = current_user.join_carts.new(join_cart_params)
    @join_cart.save
    redirect_to new_users_join_path
  end

  private
  def join_cart_params
    params.require(:join_cart).permit(:subscription_id, :user_id, :payment_method)
  end
  
end

app/controllers/users/joins_controller.rb
class Users::JoinsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @join = Join.new
    @user = current_user
    @join_carts = current_user.join_carts
  end

  def create
    @join = Join.new(join_params)
    @join.save
    redirect_to users_joins_confirm_path
  end

  def confirm
    @join_carts = current_user.join_carts
    @user = current_user
  end

  def complete
  end
  
  private
  def join_params
    params.require(:join).permit(:subscription_id, :user_id, :payment_method)
  end
  
  
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     users_subscriptions_path(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
protected
# 退会しているかを判断するメソッド
def user_state
  ## 【処理内容1】 入力されたemailからアカウントを1件取得
  @user = User.find_by(email: params[:user][:email])
  ## アカウントを取得できなかった場合、このメソッドを終了する
  return if !@user
  ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
  if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == true)
      redirect_to new_user_registration_path
  end
end
end

app/controllers/users/subscriptions_controller.rb
class Users::SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.all
  end
  
  def show
    @subscription = Subscription.find(params[:id])
    @join_cart = JoinCart.new
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  
  def unsubscribe
    @user = User.find_by(email: params[:email])
  end

  def show
    @user = current_user
    @book_carts = current_user.book_carts
    @genres = Genre.all
  end
  
  def edit
    @user = current_user
  end
  
  def update
     @user = current_user
   if @user.update(user_params)
      redirect_to users_user_path(current_user.id)
   else
      render :edit
   end
  end
  
  def withdraw
    @user = current_user
    if @user.update(is_deleted: true)
      reset_session
      redirect_to root_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :name, :address, :postal_code, :phone_number)
  end

end

app/views/users/books/_genre.html.erb
<table class="table table-bordered border border-dark">
  <thead>
    <tr>
      <th>ジャンル</th>
    </tr>
  </thead>

  <tbody>
    <% genres.each do |genre| %>
    <tr>
      <td>
        <%= genre.name %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/books/_index.html.erb
<table>
    <thead>
        <tr>
          <th></th>
          <th>タイトル</th>
          <th>説明</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
    </thead>
    <tbody id="book">
    <% books.each do |book| %>
      <tr>
        <th><%= attachment_image_tag book, :image, :fill, 100, 100, format: 'jpeg' %></th>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= link_to "詳細",users_book_path(book.id), class:"btn btn-primary" %></td>
          <td></td>
          <td></td>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/users/books/index.html.erb
  <div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render "users/users/show", users: @users %>
      <%= render "users/books/genre", genres: @genres %>
    </div>
  
    <div class="col-xs-8">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th></th>
          <th><%= sort_order "name", "タイトル" %></th>
          <th><%= sort_order "author", "作者" %></th>
          <th><%= sort_order "genre", "ジャンル" %></th>
          <th><%= sort_order "created_at", "登録順" %></th>
          <th><%#= sort_order "book_comments", "コメント数" %></th>
          <th><%#= sort_order "favorites", "いいね数" %></th>
          <th></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to users_book_path(book.id) do %>
                <%= attachment_image_tag book, :image, :fill, 100, 100, format: 'jpeg' %>
                <% end %>
              </td>
              <td><%= book.name %></td>
              <td><%= book.author %></td>
              <td><%= book.genre.name %></td>
              <td><% book.created_at %></td>
              <td><%= "#{book.comment_count(book)} コメント" %></td>
              <td><%= "#{book.favorites.count} いいね" %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/books/show.html.erb
<div class="container">
  <h2>Book詳細</h2>

    <div class="row">
    <div class="col-6">
      <%= attachment_image_tag @book,:image, size:"500x400", format: 'jpeg' %>
    </div>
    <div class="col-6" id="book_<%= @book.id %>">
      <h4><strong><%= @book.name %></strong></h4>
      <p><%= @book.author%></p>
      <p><%= @book.descript%></p>
      
        <div class="favorite"><%= render "users/favorites/favorite", book: @book %></div>
        
      コメント件数：<%= @book.book_comments.count %>
      <% if user_signed_in? %>
      <%= form_with model:@book_cart, url:users_book_carts_path, method: :post, local:true do |f|%>
      <%= f.hidden_field :book_id, value: @book.id %>
      <%= f.submit 'my本棚へ', class:"btn btn-primary" %>
      <% end %>
      <% end %>
    </div>
    </div>

      <div class="col-md-12">
        <div>
          <h3>コメント</h3>
          <table>
            <thead>
            <th>ユーザー名</th>
            <th></th>
            <th>コメント</th>
            <th>投稿時間</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </thead>
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= book_comment.user.name %></td>
              <td></td>
              <td><%= book_comment.comment %></td>
              <td><%= book_comment.created_at %></td>
              <td><% if book_comment.written_by?(current_user) %>
                  <div>
                  <%= link_to "削除", users_book_book_comments_path(book_comment.book, book_comment), method: :delete %>
                  </div>
                  <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
          </table>
        </div>
      </div>
      
      <div class="col-sm-12">
        <h3>
        <div>
          <%= form_with(model:[@book, @book_comment], url:users_book_book_comments_path(@book), local: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
        </div>
        </h3>
      </div>
  </div>
</div>